server:
  port: 8080
  address: 0.0.0.0

aviationapi:
  base-url: https://api.aviationapi.com

resilience4j:
  retry:
    instances:
      aviationApi:
        max-attempts: 3
        wait-duration: 500ms
  circuitbreaker:
    instances:
      aviationApi:
        sliding-window-size: 5
        minimum-number-of-calls: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

logging:
  level:
    root: INFO
    com.example.aviation: DEBUG
